---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/joedodson/concourse-tutorial.git
    branch: master

jobs:
- name: job-hello-world
  public: true
  serial: true
  plan:
  - get: resource-tutorial
    trigger: true
  - task: hello-world
    file: resource-tutorial/tutorials/basic/task-hello-world/task_hello_world.yml

